name = "logsfucker"
compatibility_date = "2024-01-01"

# Куда кладёт сборка фронта
pages_build_output_dir = "frontend/dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "logs-db"
database_id = "253b544c-3a8f-4783-8f7f-47df2e6e0096"

[env.preview]
vars = { ENVIRONMENT = "preview" }

[[env.preview.d1_databases]]
binding = "DB"
database_name = "logs-db"
database_id = "253b544c-3a8f-4783-8f7f-47df2e6e0096"
